//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDSoft.SqlTools.WinForms.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ModelsData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelsData() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NDSoft.SqlTools.WinForms.Resources.ModelsData", typeof(ModelsData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Approve32x32_Transparent {
            get {
                object obj = ResourceManager.GetObject("Approve32x32_Transparent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data Connection Error.
        /// </summary>
        internal static string Data_Connection_Error {
            get {
                return ResourceManager.GetString("Data_Connection_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeleteRed {
            get {
                object obj = ResourceManager.GetObject("DeleteRed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeleteRed_22x22 {
            get {
                object obj = ResourceManager.GetObject("DeleteRed_22x22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Edit {
            get {
                object obj = ResourceManager.GetObject("Edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Must be an Application Name for the connection.
        /// </summary>
        internal static string Missing_Appname {
            get {
                return ResourceManager.GetString("Missing_Appname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Must be an Authentication method.
        /// </summary>
        internal static string Missing_Auth {
            get {
                return ResourceManager.GetString("Missing_Auth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Must be a name for the connection.
        /// </summary>
        internal static string Missing_Name {
            get {
                return ResourceManager.GetString("Missing_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A Password is required.
        /// </summary>
        internal static string Missing_Pwd {
            get {
                return ResourceManager.GetString("Missing_Pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Must be a server for the connection.
        /// </summary>
        internal static string Missing_Server {
            get {
                return ResourceManager.GetString("Missing_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A user name is required.
        /// </summary>
        internal static string Missing_User {
            get {
                return ResourceManager.GetString("Missing_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NewFile {
            get {
                object obj = ResourceManager.GetObject("NewFile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] PostGres {
            get {
                object obj = ResourceManager.GetObject("PostGres", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -- Tables
        ///SELECT [TABLE_SCHEMA] AS [Schema], 
        ///       [TABLE_NAME] AS [Name]
        ///FROM [INFORMATION_SCHEMA].[TABLES] AS [Table]
        ///WHERE([TABLE_TYPE] = &apos;BASE TABLE&apos;)
        ///     AND ([TABLE_NAME] NOT LIKE &apos;sys%&apos;)
        ///     AND ([TABLE_NAME] NOT LIKE &apos;AspNet%&apos;)
        ///     AND ([TABLE_NAME] NOT LIKE &apos;__MigrationHistory&apos;)
        ///ORDER BY [Schema], 
        ///         [Name];
        ///-- Columns
        ///SELECT [COLUMN_NAME], 
        ///       [ORDINAL_POSITION], 
        ///       [COLUMN_DEFAULT], 
        ///       [IS_NULLABLE], 
        ///       [DATA_TYPE], 
        ///       [CHARACTER_MAXIMUM_LENGTH] [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string SchemaSQL {
            get {
                return ResourceManager.GetString("SchemaSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Search {
            get {
                object obj = ResourceManager.GetObject("Search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
